<?php

/**
 * MobileDetector
 *
 * Mobile device detection using https://github.com/serbanghita/Mobile-Detect
 *
 * @author maks feltrin - pine3ree <pine3ree(AT)gmail(DOT)com>
 */

class MobileDetector extends WireData implements Module
{
    public static function getModuleInfo()
    {
        return array(
            'title'    => 'Mobile Device Detector',
            'version'  => 10,
            'summary'  => 'Detect client device type',
            'author'   => 'pine3ree',
            'href'     => 'https://github.com/pine3ree/MobileDetector',
            'singular' => true,
            'autoload' => true,
            'requires' => 'Pimpled',
        );
    }

    public function ready()
    {
        if ($this->page->template == 'admin') {
            return;
        }

        static $initialized = false;

        if (!$initialized) {

            $this->addMobileDetector();

            $this->addHookBefore('Page::render', $this, 'onBeforePageRender');

            $initialized = true;
        }
    }

    public function onBeforePageRender(HookEvent $event)
    {
        return $this->enableInPage($event);
    }

    protected function addMobileDetector()
    {
        $pimple = $this->wire('pimple');

        $pimple->set('mobileDetect', function () {
            return new Detection\MobileDetect();
        });

        $this->addHookProperty('Config::mobileDetect', function (HookEvent $event) use ($pimple) {
            static $mobileDetect;
            if (null === $mobileDetect) {
                $mobileDetect = $pimple->get('mobileDetect');
            }
            $event->return = $mobileDetect;
        });

        $this->addHookProperty('Config::isMobile', function (HookEvent $event) {
            static $is_mobile = null;
            if (null === $is_mobile) {
                $is_mobile = $event->object->mobileDetect->isMobile();
            }
            $event->return = $is_mobile;
        });

        $this->addHookProperty('Config::isTablet', function (HookEvent $event) {
            static $is_tablet = null;
            if (null === $is_tablet) {
                $is_tablet = $event->object->mobileDetect->isTablet();
            }
            $event->return = $is_tablet;
        });

        $this->addHookProperty('Config::isPhone', function (HookEvent $event) {
            static $is_phone = null;
            if (null === $is_phone) {
                $is_phone = $event->object->isMobile && !$event->object->isTablet;
            }
            $event->return = $is_phone;
        });
    }

    protected function enableInPage(HookEvent $event)
    {
        $page = $event->object;

        if ($page->template == 'admin' || $page->disableMobileDetect) return;

        $config = $this->config;

        $this->addHookProperty('Page::isMobile', function (HookEvent $event) use ($config) {
            static $is_mobile = null;
            if (null === $is_mobile) {
                $is_mobile = $config->isMobile;
            }
            $event->return = $is_mobile;
        });

        $this->addHookProperty('Page::isTablet', function (HookEvent $event) use ($config) {
            static $is_tablet = null;
            if (null === $is_tablet) {
                $is_tablet = $config->isTablet;
            }
            $event->return = $is_tablet;
        });

        $this->addHookProperty('Page::isPhone', function (HookEvent $event) use ($config) {
            static $is_phone = null;
            if (null === $is_phone) {
                $is_phone = $config->isPhone;
            }
            $event->return = $is_phone;
        });
    }

    public function ___install()
    {
        if(version_compare(PHP_VERSION, '5.3.8', '<')) {
            throw new WireException("This module requires PHP 5.3.8 or newer.");
        }

        $pwVer = 100 * ProcessWire::versionMajor + 10 * ProcessWire::versionMinor + ProcessWire::versionRevision;

        if($pwVer < 250) {
            throw new WireException("This module requires ProcessWire 2.5.0 or newer.");
        }
    }
}
